### ISSUE TITLE
"This container contains a basic installation of the latest version of SageMath,"

### ISSUE THREAD

**Issue by williamstein** [sagemath/docker-images#20]
No it doesn't.   As of opening this ticket, it contains 7.0.     

Maybe it could be rephrased to: "This container contains a basic installation of some version of SageMath, which somebody happened to get around to packaging.  Please join the SageMath dev project and improve how frequently these get updated."

**Comment by embray** [comment]
Well okay, I'm sure whenever that was written it was true.  I'll work on updating the images and also backfilling any missing images for Sage versions that have come out since the current one.  The plan is to automate this process but I've had other priorities right now, and we'll also need better coordination with the release manager so that new images can be built and distributed quickly after a release.

**Comment by williamstein** [comment]
Some other thoughts, which don't belong here: 
- It seems possibly annoying to have two separate sage and sage-jupyter images.    One has to download a lot more files to just run these two (I don't know the extent to which the images are de-duped).
- It would be useful to have a sagedev docker image, which -- instead of running a single command -- sets up a working development environment and launches bash with some instructions printed (instead of a sage prompt).   Editing files and typing "sage -br" or "make" would work.    To make this really useful, it would be interesting to have the source code github repo mounted as a volume...

Sorry for spamming this issue by putting some unrelated ideas here.   In any case, thanks for making these images -- I was interviewed for https://talkpython.fm/ yesterday, and mentioned you and these images in my interview...

**Comment by embray** [comment]
> It seems possibly annoying to have two separate sage and sage-jupyter images. One has to download a lot more files to just run these two (I don't know the extent to which the images are de-duped).

I've thought some about this too.  To be clear: It does not (or should not) result in any extra downloads--the images are almost completely identical (Docker composes images out of multiple layers each with their own unique identification).  The "sage" and "sage-jupyter" images are completely identical, the latter containing just one additional instruction to launch the jupyter notebook by default, as well as expose the correct port.

Like you (I think) I'm not entirely convinced that it's helpful to have.  But I'm not convinced that it's harmful either.  We don't have enough experience with these in the wild yet to be certain

> It would be useful to have a sagedev docker image, which -- instead of running a single command -- sets up a working development environment and launches bash with some instructions printed (instead of a sage prompt). Editing files and typing "sage -br" or "make" would work. To make this really useful, it would be interesting to have the source code github repo mounted as a volume...

I agree.  Right now you can start the existing sage-develop image with bash instead of going right into the sage prompt.  That's a matter of passing the correct arguments to `docker run` or `docker create`.  But the current sage-develop image does as much as possible to clean up the image, including deleting most development related files to save space.  But we've also discussed the utility of an image _for_ developing sage, and have mostly just been stuck on bikeshedding over what to call it (it can't be sage-develop since that's already taken).  I feel like there was an issue for that but now I can't find it....

> Sorry for spamming this issue by putting some unrelated ideas here. In any case, thanks for making these images -- I was interviewed for https://talkpython.fm/ yesterday, and mentioned you and these images in my interview...

Thanks!  Again, I'll try to get them updated soon.

**Comment by embray** [comment]
Okay, I've pushed newly built images for sage 7.0, 7.1, and 7.2 and updated the sagemath/sagemath:latest tag to point to 7.2.  I also updated the sagemath-jupyter image.  Sorry for the delay.

Next working on setting up a cron job to rebuilt the -develop image nightly, as well to check for new tagged versions of sage to rebuild the sagemath/sagemath image as appropriate.
