### ISSUE TITLE
SageMath image long to start because of initialization

### ISSUE THREAD

**Issue by videlec** [sagemath/docker-images#35]
Each time the docker image is launched in a container, SageMath creates `.pyc` files for each file in the sagemath library and perform some copy. It takes a serious amount of time (~10 secs). Could it be possible for this preprocessing to be made in the image? In other word, run SageMath once in the build process.

**Comment by embray** [comment]
You should make a ticket on trac.sagemath.org which has all the current infrastructure for building docker images now (it has been merged into the main git repository for Sage). This project is no longer related to the current Docker builds. I should more clearly mark it as such (maybe archive it).

That said I don't know if it's a good idea. If it adds much size to the Docker image there's not as much point to doing it since the pyc files can always be regenerated. But we can discuss and see.

**Comment by videlec** [comment]
https://trac.sagemath.org/ticket/28040

It would indeed be nice if this github repo was archived with a mention on the README that development happens directly in the SageMath sources.
